import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Stars from "@/components/Stars";

export const metadata: Metadata = {
  title: "Just a code crafter",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-black text-white">
        <Stars />
        <div className="relative z-10">
          {" "}
          {/* Keeps content above stars */}
          {children}
        </div>
      </body>
    </html>
  );
}
